### ISSUE TITLE
Using EQ to comapre strings  test  in long-form-customized

### ISSUE THREAD

**Issue by Yehouda** [phoe/in-nomine#8]
https://github.com/phoe/in-nomine/blob/d0bef1e996d586337dd30b8a975e4ae5a09c878a/t/in-nomine.lisp#L252

The test **long-form-customized** comparing strings using **eq** like the example above (in nine places), which doesn't work. It needs to be replaced by **equal** (better than **string=** because doesn't error if the other value is not a string).

**Comment by phoe** [comment]
Thanks, good catch.
